name: Publish Library
run-name: ${{ github.actor }} is publishing ${{ github.event.repository.name }}

on:
  release:
    types: [published]


jobs:
  publish:
    env:
      VERSION: ${{ github.event.release.tag_name }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x

    - name: Build
      run: ./build.sh ${{ env.VERSION }}

    - name: Nuget Publish
      run: dotnet nuget push bin/Release/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
